on: [push]
name: Azure ARM
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - uses: actions/checkout@main

              # Log into Azure
            - uses: azure/login@v1
              with:
                  clientId: ${{ secrets.CLIENT_ID }}
                  clientSecret: ${{ secrets.CLIENT_SECRET }}
                  subscriptionId : ${{ secrets.AZURE_SUBSCRIPTION }}
                  tenantId : ${{ secrets.TENANT_ID }}
                  activeDirectoryEndpointUrl : ${{ secrets.ACTIVEDIRECTORYENDPOINTURL }}
                  resourceManagerEndpointUrl : ${{ secrets.RESOURCEMANAGERENDPOINTURL }}
                  activeDirectoryGraphResourceId : ${{ secrets.ACTIVEDIRECTORYGRAPHRESOURCEID }}
                  sqlManagementEndpointUrl : ${{ secrets.SQLMANAGEMENTENDPOINTURL }}
                  galleryEndpointUrl : ${{ secrets.GALLERYENDPOINTURL }}
                  managementEndpointUrl : ${{ secrets.MANAGEMENTENDPOINTURL }}
                  oid :  ${{ secrets.OID }}

              # Deploy Bicep file
            - name: deploy
              uses: azure/arm-deploy@v1
              with:
                  subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
                  resourceGroupName: ${{ secrets.AZURE_RG }}
                  template: ./main.bicep
                  parameters: storagePrefix=stg
                  failOnStdErr: false
